### ISSUE TITLE
Object merge with spread operator not working 

### ISSUE THREAD

**Issue by jasan-s** [vmasto/express-babel#5]
```
const person = { name: 'jasan', gender: 'Male' };
const tools = { computer: 'Mac', editor: 'sublime' };

const summary = {...person, ...tools};
```
nodemon crashes if I try to use the spread to combine the objects. Using `_.merge` instead.

**Comment by vmasto** [comment]
Thanks for the heads up. I'll see what went wrong there and add tests for future releases.

**Comment by vmasto** [comment]
Should be good now :)
