### ISSUE TITLE
Possible merge request: Add babel/minify

### ISSUE THREAD

**Issue by ndabAP** [vmasto/express-babel#73]
What do you think about:

https://github.com/babel/minify

to be added to script `build`? I'd open a merge request.

**Comment by vmasto** [comment]
Hi @ndabAP thanks for the issue. Sorry it took so long to reply. What would the benefit be of minifying server-side code?

**Comment by ndabAP** [comment]
Hey @vmasto no problem. According to [this](https://stackoverflow.com/a/38135264/6143407) answer it can help to speed up the application.

**Comment by vmasto** [comment]
It looks like for a while now inlining functions heuristics don't take string size into account so I'm assuming (as the SO post says) minification doesn't really add anything to perf. I'm hesitant to add more complexity on this particular project, I think if anyone needs to squeeze the V8 engine for negligible (from what I read) perf gains with minification it is easy enough to add it.

https://bugs.chromium.org/p/v8/issues/detail?id=3354
