### ISSUE TITLE
breakpoints not working in vs code

### ISSUE THREAD

**Issue by matepaiva** [vmasto/express-babel#8]
Hey, great work! I became a big fan of this starter kit. The only thing that didn't worked as expected were the breakpoints in vscode. I know the problem is somewhere in babel, but I have no clue about how to fix it. Do you? If you could be my tutor in this mission, I could try to fix it myself. :)

Congratz, one more time!

**Comment by vmasto** [comment]
Hey, thanks for the kind words.

It's been a bit hectic lately so I do have some love showing owed to this starter kit. I'll try to help with the first chance. Until then, could you let me know how to reproduce the problem exactly. I don't use VSCode personally.

**Comment by matepaiva** [comment]
Sorry for the late answer, @vmasto. 

Anyway, my mistake. I didn't know how to setup vs code to attach debug. Now it works. Here is how I made it happen:

1. At script `dev` on `package.json`, add --inspect flag: 
```"nodemon src/index.js --exec \"node -r dotenv/config -r babel-register\""``` 
to 
```"nodemon --inspect=22688 src/index.js --exec \"node -r dotenv/config -r babel-register\""```
2. Create a file at `.vscode/launch.json` with this configuration:
```javascript
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "attach",
      "name": "Attach",
      "port": 22688,
      "restart": true,
      "sourceMaps": true,
      "stopOnEntry": false
    }
  ]
}
```

3. After that, you start your server as usual, with `npm run dev`.

4. Press F5 to attach the debugger to the server. 

4. You will see a message: "Debugger Attached". Yay!

How do you feel about adding some of these information to the README, or to another file linked to the README? If you are good with this, I could send you a PR with this info.

**Comment by vmasto** [comment]
Glad you solved the issue! I do think this kind of info is very valuable and should be in the README file. Can you create a new section under deployment perhaps titled "Debugging" and add that info as a generic way on how to attach the debugger, then specify the `launch.json` file in a subsection for VSCode? What do you think?

**Comment by matepaiva** [comment]
Nice! I will try to work on it in the next few days.

**Comment by vmasto** [comment]
I've added a link to @matepaiva in the README file, closing this issue. Thanks a lot!
